#server:
#  port: 1001
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/a?serviceTimezone=Asia/Shanghai&useSSL=false&useUnicode=utf-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      initial-size: 1
#      max-active: 5
#      pool-prepared-statements: false
#      validation-query: select 1 from DUAL
#      validation-query-timeout: 6000
#      test-on-borrow: true
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 90000
#      min-evictable-idle-time-millis: 30000
#mybatis:
#  mapper-locations: classpath:mybatis_mapper/*.xml
#  configuration:
#    use-generated-keys: true
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl