server:
  port: 1002

spring:
  application:
    name: service-b

#spring:
#  application:
#    name: service-b
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config
#      fail-fast: true
#      retry:
#        initial-interval: 2000
#        max-interval: 10000
#        multiplier: 2
#        max-attempts: 10