server:
  port: 1003
spring:
  application:
    name: service-rabbitmq

  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /rabbit_host
    connection-timeout: 15000
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true